import { createSlice } from '@reduxjs/toolkit';

const earthRegions = [
  {
    name: 'Đông Nam Á',
    animals: ['Voi', 'Hổ', 'Khỉ', 'Chim Paramok'],
    culture: 'Chùa chiền, lễ hội truyền thống',
    cuisine: ['Phở', 'Pad Thai', 'Cơm Cà Ri', 'Bánh mì'],
  },
  {
    name: 'Châu Âu',
    animals: ['Gấu', 'Sói', 'Đại Bàng', 'Nai'],
    culture: 'Lâu đài, nhạc cổ điển',
    cuisine: ['Pizza', 'Pasta', 'Bánh mì Pháp', 'Bia'],
  },
  {
    name: 'Châu Phi',
    animals: ['Sư tử', 'Hươu cao cổ', 'Voi Châu Phi', 'Tê giác'],
    culture: 'Váy Afrika, lễ hội múa',
    cuisine: ['Tajine', 'Jollof Rice', 'Ugali', 'Injera'],
  },
  {
    name: 'Mỹ Latinh',
    animals: ['Sư tử núi', 'Báo', 'Lạc đà', 'Macaw'],
    culture: 'Carnival, Điêu khắc Aztec',
    cuisine: ['Tacos', 'Ceviche', 'Chili Con Carne', 'Chocolate'],
  },
];

const initialState = {
  planets: [
    {
      id: 0,
      name: 'Mặt Trời',
      emoji: '☀️',
      color: '#FFD700',
      description: 'Sao cha của hệ mặt trời',
      type: 'star',
      mass: '1.989 × 10³⁰ kg',
      isSun: true,
      orbitRadius: 0,
      orbitDuration: 0,
      size: 'Siêu lớn',
    },
    {
      id: 1,
      name: 'Thủy Tinh',
      emoji: '☿️',
      color: '#A5A5A5',
      description: 'Hành tinh nhỏ nhất và gần Mặt Trời nhất.',
      type: 'planet',
      mass: '3.30 × 10²³ kg',
      diameter: '4,879 km',
      climate: 'Cực kỳ khắc nghiệt',
      temperature: '427°C / -173°C',
      distance: '0.39 AU',
      distanceAU: 0.39,
      inclination: 7.0,
      orbitalPeriod: 0.24,
      gravity: '3.7 m/s²',
      moons: 0,
      orbitRadius: 60,
      initialAngle: Math.random() * Math.PI * 2,
      selected: false,
    },
    {
      id: 2,
      name: 'Kim Tinh',
      emoji: '♀️',
      color: '#E3BB76',
      description: 'Hành tinh nóng nhất do hiệu ứng nhà kính.',
      type: 'planet',
      mass: '4.87 × 10²⁴ kg',
      diameter: '12,104 km',
      climate: 'Địa ngục trần gian',
      temperature: '462°C',
      distance: '0.72 AU',
      distanceAU: 0.72,
      inclination: 3.4,
      orbitalPeriod: 0.62,
      gravity: '8.9 m/s²',
      moons: 0,
      orbitRadius: 90,
      initialAngle: Math.random() * Math.PI * 2,
      selected: false,
    },
    {
      id: 3,
      name: 'Trái Đất',
      emoji: '🌍',
      color: '#2271B3',
      description: 'Hành tinh duy nhất có sự sống được biết đến.',
      type: 'planet',
      mass: '5.97 × 10²⁴ kg',
      diameter: '12,742 km',
      climate: 'Lý tưởng cho sự sống',
      temperature: '15°C',
      distance: '1.00 AU',
      distanceAU: 1.00,
      inclination: 0,
      orbitalPeriod: 1.00,
      gravity: '9.8 m/s²',
      moons: 1,
      orbitRadius: 130,
      initialAngle: Math.random() * Math.PI * 2,
      regions: earthRegions,
      moon: {
        id: 'moon_1',
        name: 'Mặt Trăng',
        emoji: '🌙',
        isMoon: true,
        color: '#C8C4BE',
        description: 'Vệ tinh tự nhiên duy nhất của Trái Đất.',
        diameter: '3,474 km',
        distance: '384,400 km',
        orbitalPeriod: 0.0748,
        orbitRadius: 35,
        initialAngle: Math.random() * Math.PI * 2,
      },
      selected: false,
    },
    {
      id: 4,
      name: 'Hỏa Tinh',
      emoji: '♂️',
      color: '#E27B58',
      description: 'Hành tinh đỏ với những ngọn núi lửa khổng lồ.',
      type: 'planet',
      mass: '6.42 × 10²³ kg',
      diameter: '6,779 km',
      climate: 'Lạnh và bụi bặm',
      temperature: '-65°C',
      distance: '1.52 AU',
      distanceAU: 1.52,
      inclination: 1.9,
      orbitalPeriod: 1.88,
      gravity: '3.7 m/s²',
      moons: 2,
      orbitRadius: 180,
      initialAngle: Math.random() * Math.PI * 2,
      selected: false,
    },
    {
      id: 5,
      name: 'Mộc Tinh',
      emoji: '♃',
      color: '#D39C7E',
      description: 'Gã khổng lồ khí lớn nhất hệ mặt trời.',
      type: 'planet',
      mass: '1.90 × 10²⁷ kg',
      diameter: '139,820 km',
      climate: 'Bão tố vĩnh cửu',
      temperature: '-110°C',
      distance: '5.20 AU',
      distanceAU: 5.20,
      inclination: 1.3,
      orbitalPeriod: 11.86,
      gravity: '24.8 m/s²',
      moons: 95,
      orbitRadius: 300,
      initialAngle: Math.random() * Math.PI * 2,
      selected: false,
    },
    {
      id: 6,
      name: 'Thổ Tinh',
      emoji: '♄',
      color: '#C5AB6E',
      description: 'Nổi tiếng với hệ thống vành đai lộng lẫy.',
      type: 'planet',
      mass: '5.68 × 10²⁶ kg',
      diameter: '116,460 km',
      climate: 'Gió siêu tốc',
      temperature: '-140°C',
      distance: '9.54 AU',
      distanceAU: 9.54,
      inclination: 2.5,
      orbitalPeriod: 29.45,
      gravity: '10.4 m/s²',
      moons: 146,
      orbitRadius: 400,
      initialAngle: Math.random() * Math.PI * 2,
      selected: false,
    },
    {
      id: 7,
      name: 'Thiên Vương Tinh',
      emoji: '♅',
      color: '#B5E3E3',
      description: 'Hành tinh băng khổng lồ quay nghiêng.',
      type: 'planet',
      mass: '8.68 × 10²⁵ kg',
      diameter: '50,724 km',
      climate: 'Cực lạnh',
      temperature: '-195°C',
      distance: '19.2 AU',
      distanceAU: 19.2,
      inclination: 0.8,
      orbitalPeriod: 84.0,
      gravity: '8.7 m/s²',
      moons: 28,
      orbitRadius: 500,
      initialAngle: Math.random() * Math.PI * 2,
      selected: false,
    },
    {
      id: 8,
      name: 'Hải Vương Tinh',
      emoji: '♆',
      color: '#3E54E8',
      description: 'Hành tinh xanh thẳm xa xôi và lộng gió.',
      type: 'planet',
      mass: '1.02 × 10²⁶ kg',
      diameter: '49,244 km',
      climate: 'Gió mạnh nhất',
      temperature: '-201°C',
      distance: '30.1 AU',
      distanceAU: 30.1,
      inclination: 1.8,
      orbitalPeriod: 164.8,
      gravity: '11.15 m/s²',
      moons: 14,
      orbitRadius: 600,
      initialAngle: Math.random() * Math.PI * 2,
      selected: false,
    },
  ],
};

const planetsSlice = createSlice({
  name: 'planets',
  initialState,
  reducers: {
    selectPlanet: (state, action) => {
      state.planets = state.planets.map((planet) =>
        planet.id === action.payload
          ? { ...planet, selected: true }
          : { ...planet, selected: false }
      );
    },
    deselectPlanet: (state) => {
      state.planets = state.planets.map((planet) => ({
        ...planet,
        selected: false,
      }));
    },
  },
});

export const { selectPlanet, deselectPlanet } = planetsSlice.actions;
export default planetsSlice.reducer;
